name: Sync release_for_deploy to production

on:
  schedule:
    - cron: '0 0 * * *'  # Roda a cada hora
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório GoPlay
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: production  # Clonamos a branch production para atualizar

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Adicionar remoto do repositório de origem
        run: |
          git remote add upstream https://github.com/IzabelleCC/Fatec-Ipiranga-LabEngSoft-N-2025-1-G15-GoPlay.git
          git fetch upstream

      - name: Merge da branch release_for_deploy
        run: |
          git merge upstream/release_for_deploy --allow-unrelated-histories --no-edit || true

      - name: Push para a branch production
        run: |
          git push origin production
