// <auto-generated />
using System;
using GoPlay_UserManagementService_Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoPlay_UserManagementService_Infra.Migrations
{
    [DbContext(typeof(GoPlayContext))]
    [Migration("20250309222636_GOP-13-Initial")]
    partial class GOP13Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoPlay_UserManagementService_Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_USER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("GENDER");

                    b.Property<string>("InstagramPage")
                        .HasColumnType("text")
                        .HasColumnName("INSTAGRAMP_PAGE");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("TShirtSize")
                        .HasColumnType("text")
                        .HasColumnName("TSHIRT_SIZE");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("USER_TYPE");

                    b.HasKey("IdUser");

                    b.ToTable("USER", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
