name: Sync procuction to target repo

on:
  push:
    branches:
      - procuction

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to destination repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'

          git remote add target https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/IzabelleCC/GoPlay.git

          git push --force target procuction:procuction
